---
# - hosts: "app_north_virginia_lex_dev"
- hosts: "{{ deploy_host_name }}"
  become: yes
  strategy: free
  vars_files:
    - "vars/main.yml"
  roles:
    - role: deploy-agridex-playground
      tags: [deploy-agridex-playground]
    - role: deploy-mock-bank-ui
      tags: [deploy-mock-bank-ui]
    - role: stack-proxy
      tags: [stack-proxy]
    