---
# - hosts: "app_north_virginia_lex_dev"
- hosts: "{{ deploy_host_name }}"
  become: yes
  strategy: free
  vars_files:
    - "vars/main.yml"
  roles:
    - role: deploy-agridex-playground
      tags: [deploy-agridex-playground]
    - role: deploy-mock-bank-ui
      tags: [deploy-mock-bank-ui]
    - role: deploy-konnect-playground
      tags: [deploy-konnect-playground]
    - role: deploy-konnect-docs
      tags: [deploy-konnect-docs]  
    - role: deploy-resolver
      tags: [deploy-resolver]  
    - role: deploy-gatekeeper
      tags: [deploy-gatekeeper]
    - role: deploy-agridex-beckn
      tags: [deploy-agridex-beckn]
    - role: stack-proxy
      tags: [stack-proxy]
    - role: deploy-fusion-auth
      tags: [deploy-fusion-auth]
    