---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_konnect_playground_service }}.yml"
env_file_name: "{{ service_konnect_playground_service }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: konnect-playground


docker_port: "{{ service_konnect_playground_docker_port }}"
host_port: "{{ service_konnect_playground_host_port }}"
image_name: "{{ image_konnect_playground_service }}"
tag: "{{ tags_konnect_playground_service }}"
replicas: "{{ service_replicas_konnect_playground_service }}"
network_alias_name: "{{ network_alias_konnect_playground_service }}"
docker_service_stack_name: konnect
docker_service_name: "{{ service_konnect_playground_service }}"
force_reload: "{{ force_reload_konnect_playground_service }}"
host_logs_location: "{{ konnect_playground_logs }}"
docker_logs_location: /logs

# Your credentials on the vault
# credentials: "{{ lookup('hashi_vault', 'secret={{ esamwad_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"
