---
# vars file for deploy-sb-ext
# For script
template_compose_file_name: compose-file.j2
template_env_file_name: env.j2
compose_file_name: "{{ service_mock_bank_ui_service }}.yml"
env_file_name: "{{ service_mock_bank_ui_service }}.env"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
user_friendly_name: mock bank ui


docker_port: "{{ service_mock_bank_ui_docker_port }}"
host_port: "{{ service_mock_bank_ui_host_port }}"
image_name: "{{ image_mock_bank_ui_service }}"
tag: "{{ tags_mock_bank_ui_service }}"
replicas: "{{ service_replicas_mock_bank_ui_service }}"
network_alias_name: "{{ network_alias_mock_bank_ui_service }}"
docker_service_stack_name: konnect
docker_service_name: "{{ service_mock_bank_ui_service }}"
force_reload: "{{ force_reload_mock_bank_ui_service }}"
host_logs_location: "{{ mock_bank_ui_logs }}"
docker_logs_location: /logs

# Your credentials on the vault
# credentials: "{{ lookup('hashi_vault', 'secret={{ esamwad_secret_path }}', url=VAULT_ADDR, token=VAULT_TOKEN) }}"
